---
# Copyright 2020 Google LLC.
# This software is provided as-is, without warranty or representation for any use or purpose.
# Your use of it is subject to your agreement with Google.
- name: "Install HTCondor"
  hosts: localhost
  become: true

  tasks:
    - name: Download HTCondor repo
      get_url:
        url: https://research.cs.wisc.edu/htcondor/yum/repo.d/htcondor-stable-rhel7.repo
        force: yes
        dest: /etc/yum.repos.d/htcondor-stable-rhel7.repo

    - rpm_key:
        state: present
        key: https://research.cs.wisc.edu/htcondor/yum/RPM-GPG-KEY-HTCondor

    - name: install HTCondor and Dependencies
      yum:
        name: condor
        state: latest

    - name: Download Pegasus repo
      get_url:
        url: https://download.pegasus.isi.edu/pegasus/rhel/7/pegasus.repo
        force: yes
        dest: /etc/yum.repos.d/pegasus.repo

    - name: install Pagasus
      yum:
        name: pegasus
        state: latest